/*
 * VAVA project
 * Esport League by Martin Schön and Peter Smreček
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui.league;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import sk.stu.fiit.data.InputProcessor;
import sk.stu.fiit.league.League;
import sk.stu.fiit.league.Match;
import sk.stu.fiit.league.Prize;

/**
 *
 * @author PeterSmrecek
 */
public class LeagueInfoWindow extends javax.swing.JFrame {
    /**
     * Creates new form Template
     */
    private final Logger logger = Logger.getLogger(LeagueInfoWindow.class.getName());
    private final League league;
    
    
    public LeagueInfoWindow(League league){
        this.league = league;
        initComponents();
        loadData();
   }

    
    private void loadData(){
        nameTf.setText(this.league.getName());
        gameTf.setText(this.league.getGame());
        genreTf.setText(this.league.getGenre());
        dateStartTf.setText(InputProcessor.dateToString(this.league.getStartDate()));
        dateEndTf.setText(InputProcessor.dateToString(this.league.getEndDate()));
        ageRestrictionTf.setText(String.valueOf(this.league.getMinimalAge()));
        maxTeamsTf.setText(String.valueOf(this.league.getMaxNumberTeams()));
        teamsInMatchTf.setText(String.valueOf(this.league.getNumberOfTeamsInMatch()));
        descriptionTa.setText(this.league.getDescription());
        imageLbl.setIcon(this.league.getIcon());
        
        ArrayList<Prize> prizeList = new ArrayList<>();
        league.getPrizeList().forEach(prize -> {
            prizeList.add(prize);
        });
        populatePrizesTbl(prizeList);
        
        populateMatchesTb(league.getMatchList());
        
        logger.info("Information about league "+this.league.getName()+" displayed");
        this.setVisible(true);
    }
     
    private void populatePrizesTbl(ArrayList<Prize> prizeList) {
        DefaultTableModel model = (DefaultTableModel) tableTbl.getModel();
        deleteRows(model);

        int numberOfColumns = tableTbl.getColumnCount();
        Object[] rowData = new Object[numberOfColumns];

        for (Prize prize : prizeList) {
            rowData[0] = prize.getPosition();
            rowData[1] = prize.getName();
            rowData[2] = prize.getDescription();
            rowData[3] = prize.getPrice();
            model.addRow(rowData);
        }
    }
    
    private void populateMatchesTb(ArrayList<Match> matchesList){
        DefaultTableModel model = (DefaultTableModel) matchesTable.getModel();
        deleteRows(model);
        
        int numberOfColumns = matchesTable.getColumnCount();
        Object[] rowData = new Object[numberOfColumns];
        for(Match match : matchesList){
            rowData[0] = match.getWinner();
            rowData[1] = match.getResult();
            rowData[2] = InputProcessor.dateToString(match.getDate());
            rowData[3] = match.getType();
            model.addRow(rowData);
        
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg1Bg = new javax.swing.ButtonGroup();
        mainPnl = new javax.swing.JPanel();
        tableScroll = new javax.swing.JScrollPane();
        tableTbl = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        imagePnl = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        controlsPnl = new javax.swing.JPanel();
        matchInfoLeagueBtn = new javax.swing.JButton();
        linkButton = new javax.swing.JButton();
        infoPnl = new javax.swing.JPanel();
        l3Lbl = new javax.swing.JLabel();
        l6Lbl = new javax.swing.JLabel();
        dateEndTf = new javax.swing.JTextField();
        l9Lbl = new javax.swing.JLabel();
        l1Lbl = new javax.swing.JLabel();
        maxTeamsTf = new javax.swing.JTextField();
        l8Lbl = new javax.swing.JLabel();
        dateStartTf = new javax.swing.JTextField();
        gameTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        l5Lbl = new javax.swing.JLabel();
        genreTf = new javax.swing.JTextField();
        l2Lbl = new javax.swing.JLabel();
        teamsInMatchTf = new javax.swing.JTextField();
        ageRestrictionTf = new javax.swing.JTextField();
        l7Lbl = new javax.swing.JLabel();
        matchesScroll = new javax.swing.JScrollPane();
        matchesTable = new javax.swing.JTable();
        descriptionPnl = new javax.swing.JPanel();
        l4Lbl = new javax.swing.JLabel();
        descriptionSp = new javax.swing.JScrollPane();
        descriptionTa = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informácie o lige");

        java.awt.GridBagLayout mainPnlLayout = new java.awt.GridBagLayout();
        mainPnlLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        mainPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        mainPnl.setLayout(mainPnlLayout);

        tableScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Výhry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        tableScroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableScroll.setMinimumSize(new java.awt.Dimension(453, 200));
        tableScroll.setPreferredSize(new java.awt.Dimension(453, 200));

        tableTbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umiestnenie", "Názov výhry", "Popis", "Finančná hodnota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableTbl.getTableHeader().setReorderingAllowed(false);
        tableScroll.setViewportView(tableTbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(tableScroll, gridBagConstraints);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLbl.setText("Informácie o lige");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 20;
        mainPnl.add(titleLbl, gridBagConstraints);

        imagePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obrázok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        imagePnl.setLayout(new java.awt.GridBagLayout());

        imageLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imageLbl.setMinimumSize(new java.awt.Dimension(280, 280));
        imageLbl.setPreferredSize(new java.awt.Dimension(280, 280));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        imagePnl.add(imageLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(imagePnl, gridBagConstraints);

        controlsPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ovládacie prvky", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        controlsPnl.setLayout(new javax.swing.BoxLayout(controlsPnl, javax.swing.BoxLayout.LINE_AXIS));

        matchInfoLeagueBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matchInfoLeagueBtn.setText("Informácie o zvolenom zápase");
        matchInfoLeagueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                matchInfoLeagueBtnMouseReleased(evt);
            }
        });
        controlsPnl.add(matchInfoLeagueBtn);

        linkButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkButton.setText("Link na zápas");
        linkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                linkButtonMouseReleased(evt);
            }
        });
        controlsPnl.add(linkButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(controlsPnl, gridBagConstraints);

        infoPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informácie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        java.awt.GridBagLayout infoPnlLayout = new java.awt.GridBagLayout();
        infoPnlLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        infoPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        infoPnl.setLayout(infoPnlLayout);

        l3Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l3Lbl.setText("Žáner");
        l3Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l3Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        infoPnl.add(l3Lbl, gridBagConstraints);

        l6Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l6Lbl.setText("Dátum ukončenia");
        l6Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l6Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        infoPnl.add(l6Lbl, gridBagConstraints);

        dateEndTf.setEditable(false);
        dateEndTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateEndTf.setMinimumSize(new java.awt.Dimension(200, 26));
        dateEndTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(dateEndTf, gridBagConstraints);

        l9Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l9Lbl.setText("Počet tímov v zápase");
        l9Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l9Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        infoPnl.add(l9Lbl, gridBagConstraints);

        l1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l1Lbl.setText("Názov ligy");
        l1Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l1Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        infoPnl.add(l1Lbl, gridBagConstraints);

        maxTeamsTf.setEditable(false);
        maxTeamsTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxTeamsTf.setMinimumSize(new java.awt.Dimension(200, 26));
        maxTeamsTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(maxTeamsTf, gridBagConstraints);

        l8Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l8Lbl.setText("Maximálny počet tímov");
        l8Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l8Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        infoPnl.add(l8Lbl, gridBagConstraints);

        dateStartTf.setEditable(false);
        dateStartTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateStartTf.setMinimumSize(new java.awt.Dimension(200, 26));
        dateStartTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(dateStartTf, gridBagConstraints);

        gameTf.setEditable(false);
        gameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gameTf.setMinimumSize(new java.awt.Dimension(200, 26));
        gameTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(gameTf, gridBagConstraints);

        nameTf.setEditable(false);
        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTf.setMinimumSize(new java.awt.Dimension(200, 26));
        nameTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(nameTf, gridBagConstraints);

        l5Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l5Lbl.setText("Dátum začiatku");
        l5Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l5Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        infoPnl.add(l5Lbl, gridBagConstraints);

        genreTf.setEditable(false);
        genreTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genreTf.setMinimumSize(new java.awt.Dimension(200, 26));
        genreTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(genreTf, gridBagConstraints);

        l2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l2Lbl.setText("Hra");
        l2Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l2Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        infoPnl.add(l2Lbl, gridBagConstraints);

        teamsInMatchTf.setEditable(false);
        teamsInMatchTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamsInMatchTf.setMinimumSize(new java.awt.Dimension(200, 26));
        teamsInMatchTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(teamsInMatchTf, gridBagConstraints);

        ageRestrictionTf.setEditable(false);
        ageRestrictionTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageRestrictionTf.setMinimumSize(new java.awt.Dimension(200, 26));
        ageRestrictionTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(ageRestrictionTf, gridBagConstraints);

        l7Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l7Lbl.setText("Vekové obmedzenie");
        l7Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l7Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        infoPnl.add(l7Lbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(infoPnl, gridBagConstraints);

        matchesScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zápasy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        matchesScroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        matchesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Víťaz", "Skóre", "Dátum", "Typ zápasu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        matchesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        matchesScroll.setViewportView(matchesTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(matchesScroll, gridBagConstraints);

        descriptionPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Popis ligy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        descriptionPnl.setMinimumSize(new java.awt.Dimension(230, 77));
        java.awt.GridBagLayout descriptionPnlLayout = new java.awt.GridBagLayout();
        descriptionPnlLayout.columnWidths = new int[] {0};
        descriptionPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        descriptionPnl.setLayout(descriptionPnlLayout);

        l4Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l4Lbl.setText("Popis");
        l4Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l4Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        descriptionPnl.add(l4Lbl, gridBagConstraints);

        descriptionSp.setPreferredSize(new java.awt.Dimension(100, 240));
        descriptionSp.setRequestFocusEnabled(false);

        descriptionTa.setEditable(false);
        descriptionTa.setColumns(20);
        descriptionTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTa.setLineWrap(true);
        descriptionTa.setRows(5);
        descriptionTa.setWrapStyleWord(true);
        descriptionSp.setViewportView(descriptionTa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        descriptionPnl.add(descriptionSp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(descriptionPnl, gridBagConstraints);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Súbor");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Otvoriť");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Uložiť");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Uložiť ako");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Skončiť");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Upraviť");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Vystrihnúť");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Kopírovať");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Prilepiť");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Vymazať");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Pomocník");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Obsah");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("O aplikácií");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void matchInfoLeagueBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchInfoLeagueBtnMouseReleased
        if (matchesTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vyber zápas z tabuľky zápasov", "Problém s výberom", JOptionPane.WARNING_MESSAGE);
            logger.error("Trying to see more match info without selected row");
            return;
        }
        MatchInfoWindow matchInfoWindow = new MatchInfoWindow(this.league.getMatchList().get(matchesTable.getSelectedRow()));
    }//GEN-LAST:event_matchInfoLeagueBtnMouseReleased

    private void linkButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkButtonMouseReleased
        if (matchesTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vyber zápas z tabuľky zápasov", "Problém s výberom", JOptionPane.WARNING_MESSAGE);
            logger.error("Trying to see match link without selected row");
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Link:\n "+this.league.getMatchList().get(matchesTable.getSelectedRow()).getActiveLink(), "Link na livestream", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_linkButtonMouseReleased

    private void deleteRows(DefaultTableModel model) {
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField ageRestrictionTf;
    private javax.swing.ButtonGroup bg1Bg;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JPanel controlsPnl;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JTextField dateEndTf;
    private javax.swing.JTextField dateStartTf;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JPanel descriptionPnl;
    private javax.swing.JScrollPane descriptionSp;
    private javax.swing.JTextArea descriptionTa;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField gameTf;
    private javax.swing.JTextField genreTf;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JPanel imagePnl;
    private javax.swing.JPanel infoPnl;
    private javax.swing.JLabel l1Lbl;
    private javax.swing.JLabel l2Lbl;
    private javax.swing.JLabel l3Lbl;
    private javax.swing.JLabel l4Lbl;
    private javax.swing.JLabel l5Lbl;
    private javax.swing.JLabel l6Lbl;
    private javax.swing.JLabel l7Lbl;
    private javax.swing.JLabel l8Lbl;
    private javax.swing.JLabel l9Lbl;
    private javax.swing.JButton linkButton;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JButton matchInfoLeagueBtn;
    private javax.swing.JScrollPane matchesScroll;
    private javax.swing.JTable matchesTable;
    private javax.swing.JTextField maxTeamsTf;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nameTf;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JTable tableTbl;
    private javax.swing.JTextField teamsInMatchTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    }
