/*
 * VAVA project
 * Esport League by Martin Schön and Peter Smreček
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui.league;

import sk.stu.fiit.data.InputProcessor;
import sk.stu.fiit.league.Match;

/**
 *
 * @author schon
 */
public class MatchInfoWindow extends javax.swing.JFrame {
    private final Match match;
    
    /**
     * Creates new form MatchInfoWindow
     * @param match
     */
    public MatchInfoWindow(Match match) {
        initComponents();
        this.match = match;
        showInfo();
    }

    private void showInfo(){
        winnerLabel.setText(match.getWinner());
        resultLabel.setText(match.getResult());
        typeLabel.setText(match.getType());
        timeLabel.setText(InputProcessor.dateToStringTime(match.getDate()));
        
        teamsList.setListData(getTeams());
        
        this.setVisible(true);
    }
    
    public String[] getTeams(){
        String [] teams = new String[this.match.getTeamList().size()];
        
        for(int item = 0; item < this.match.getTeamList().size(); item++)
            teams[item] = this.match.getTeamList().get(item).getName();
        return teams;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamsList = new javax.swing.JList<>();
        teamsInfoLabel = new javax.swing.JLabel();
        winnerInfoLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        timeInfoLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        resultInfoLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        typeInfoLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informácie o zápase");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teamsList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(teamsList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 240));

        teamsInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        teamsInfoLabel.setText("Zúčastnené tímy");
        jPanel1.add(teamsInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        winnerInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        winnerInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerInfoLabel.setText("Víťaz");
        jPanel1.add(winnerInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 20, 250, -1));
        winnerInfoLabel.getAccessibleContext().setAccessibleName("");

        winnerLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        winnerLabel.setForeground(new java.awt.Color(0, 51, 102));
        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setText("------");
        jPanel1.add(winnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 50, 250, -1));
        winnerLabel.getAccessibleContext().setAccessibleName("");

        timeInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timeInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeInfoLabel.setText("Dátum a čas konania");
        jPanel1.add(timeInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 180, 250, -1));
        timeInfoLabel.getAccessibleContext().setAccessibleName("");

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("jLabel5");
        jPanel1.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 210, 250, -1));
        timeLabel.getAccessibleContext().setAccessibleName("");

        resultInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultInfoLabel.setText("Výsledok");
        jPanel1.add(resultInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 100, 250, -1));
        resultInfoLabel.getAccessibleContext().setAccessibleName("");

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("jLabel7");
        jPanel1.add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 130, 250, -1));
        resultLabel.getAccessibleContext().setAccessibleName("");

        typeInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        typeInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeInfoLabel.setText("Typ");
        jPanel1.add(typeInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 260, 250, -1));
        typeInfoLabel.getAccessibleContext().setAccessibleName("");

        typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("jLabel9");
        jPanel1.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 290, 250, -1));
        typeLabel.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 556, 374));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultInfoLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel teamsInfoLabel;
    private javax.swing.JList<String> teamsList;
    private javax.swing.JLabel timeInfoLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel typeInfoLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel winnerInfoLabel;
    private javax.swing.JLabel winnerLabel;
    // End of variables declaration//GEN-END:variables
}
