/*
 * VAVA project
 * Esport League by Martin Schön and Peter Smreček
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui.user.message;


import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import sk.stu.fiit.data.InputProcessor;
import sk.stu.fiit.data.Lists;
import sk.stu.fiit.gui.MainGui;
import sk.stu.fiit.user.Player;
import sk.stu.fiit.user.User;
import sk.stu.fiit.user.message.Message;

/**
 * Class <code>MessageWindow</code> is used as graphical interface for chat
 * function. User can access {@link NewInvitationWindow}, {@link SeeMessageWindow} 
 * and {@link NewMessageWindow}.
 * 
 * @see NewInvitationWindow
 * @see SeeMessageWindow
 * @see NewMessageWindow
 */
public class MessageWindow extends javax.swing.JFrame {
    private final User loggedUser;
    private final Lists lists;
    private final MainGui mainGui;
    
    public MessageWindow(User user, Lists lists, MainGui mainGui){
        initComponents();
        this.loggedUser = user;
        this.lists = lists;
        this.mainGui = mainGui;
        updateAll();
    }
    
    public final void updateAll(){
        String[] messages = new String[this.loggedUser.getMessages().size()];
        
        for(int item = 0; item < this.loggedUser.getMessages().size(); item++){
            Message message = this.loggedUser.getMessages().get(item);
            messages[item] = message.getSender().getNickname()+" zo dňa "+
                    InputProcessor.dateToString(message.getSendingTime())+
                    ".   "+message.getHead();
        }
        messagesList.setListData(messages);

        teamInvitationButton.setVisible(false);
        if(loggedUser.getClass().getSimpleName().equals("Player"))
            if(((Player)loggedUser).isAdmin())
                teamInvitationButton.setVisible(true);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        messagesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagesList = new javax.swing.JList<>();
        readMessageButton = new javax.swing.JButton();
        newMessageButton = new javax.swing.JButton();
        teamInvitationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Schránka správ");
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(589, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(589, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 400));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        messagesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messagesLabel.setText("Prijaté správy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        jPanel1.add(messagesLabel, gridBagConstraints);

        messagesList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messagesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        messagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(messagesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        readMessageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        readMessageButton.setText("Prečítať správu");
        readMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                readMessageButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanel1.add(readMessageButton, gridBagConstraints);

        newMessageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newMessageButton.setText("Nová správa");
        newMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newMessageButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        jPanel1.add(newMessageButton, gridBagConstraints);

        teamInvitationButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInvitationButton.setText("Nová pozvánka");
        teamInvitationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                teamInvitationButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        jPanel1.add(teamInvitationButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamInvitationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamInvitationButtonMouseReleased
        NewInvitationWindow newInvitationWindow = new NewInvitationWindow(this.loggedUser, this.lists);
    }//GEN-LAST:event_teamInvitationButtonMouseReleased

    private void newMessageButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMessageButtonMouseReleased
        NewMessageWindow newMessage = new NewMessageWindow(this.loggedUser, this.lists, this);
    }//GEN-LAST:event_newMessageButtonMouseReleased

    private void readMessageButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readMessageButtonMouseReleased
        for(int index = 0; index < this.loggedUser.getMessages().size(); index++){
            if(messagesList.isSelectedIndex(index)){
                SeeMessageWindow seeMessageWindow = new SeeMessageWindow(loggedUser, loggedUser.getMessages().get(index), this, this.mainGui);
                return;
            }     
        }
        JOptionPane.showMessageDialog(rootPane, "Vyber sprácu, ktorú chceš zobraziť", "Nemožno načítať správu", JOptionPane.WARNING_MESSAGE);
        Logger.getLogger(this.getClass().getName()).error("User didn't choose message to display");
    }//GEN-LAST:event_readMessageButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messagesLabel;
    private javax.swing.JList<String> messagesList;
    private javax.swing.JButton newMessageButton;
    private javax.swing.JButton readMessageButton;
    private javax.swing.JButton teamInvitationButton;
    // End of variables declaration//GEN-END:variables
}
