/*
 * VAVA project
 * Esport League by Martin Schön and Peter Smreček
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui.user.message;

import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import sk.stu.fiit.gui.MainGui;
import sk.stu.fiit.user.Player;
import sk.stu.fiit.user.User;
import sk.stu.fiit.user.message.Message;
import sk.stu.fiit.user.message.TeamInvitation;

/**
 * In <code>SeeMessageWindow</code> {@link User} can see full received {@link Message} 
 * or {@link TeamInvitation}. It allows them to delete messages and accept TeamInvitations.
 * 
 * @see User
 * @see Message
 * @see TeamInvitation
 */
public class SeeMessageWindow extends javax.swing.JFrame {
    private final Message message;
    private final User user;
    private final MessageWindow messageWindow;
    private final Logger logger = Logger.getLogger(this.getClass().getName());
    private final MainGui mainGui;
    
    public SeeMessageWindow(User user, Message message, MessageWindow messageWindow, MainGui mainGui) {
        initComponents();
        this.user = user;
        this.message = message;
        this.messageWindow = messageWindow;
        this.mainGui = mainGui;
        updateAll();
    }
    
    private void updateAll(){
        invitationAcceptButton.setVisible(false);
        if(message.getClass().getSimpleName().equals("TeamInvitation")){
            invitationAcceptButton.setVisible(true);
        }
        headerTextField.setText(this.message.getHead());
        bodyTextArea.setText(this.message.getBody());
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        invitationAcceptButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zobrazenie správy");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(585, 473));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerTextField.setEditable(false);
        headerTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(headerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, -1));

        bodyTextArea.setEditable(false);
        bodyTextArea.setColumns(20);
        bodyTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bodyTextArea.setLineWrap(true);
        bodyTextArea.setRows(5);
        bodyTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(bodyTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 340, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Predmet");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Správa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        invitationAcceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invitationAcceptButton.setText("Prijať pozvánku");
        invitationAcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                invitationAcceptButtonMouseReleased(evt);
            }
        });
        jPanel1.add(invitationAcceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteButton.setText("Vymazať");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonMouseReleased(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete(){
       user.getMessages().remove(this.message);
       this.messageWindow.updateAll();
       this.dispose();
    }
    private void deleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseReleased
        delete();
        logger.info("Message succesfully deleted");
    }//GEN-LAST:event_deleteButtonMouseReleased

    private void invitationAcceptButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invitationAcceptButtonMouseReleased
        if(((Player)this.user).getTeam() != null){
            JOptionPane.showMessageDialog(rootPane, "Na prijatie pozvánky do tímu nemôžeš byť v tíme!", "Nemožno prijať pozvánku", JOptionPane.WARNING_MESSAGE);
            logger.error("Player "+this.user.getNickname()+" trying to accept invitation even while being team member");
            return;
        }
        ((TeamInvitation)this.message).getTeam().addPlayer((Player)this.user);
        delete();
        this.mainGui.checkPlayerButtons();
        logger.info("Invitation accepted and deleted");
    }//GEN-LAST:event_invitationAcceptButtonMouseReleased

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bodyTextArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField headerTextField;
    private javax.swing.JButton invitationAcceptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
