/*
 * VAVA assignment 3
 * Room booking by Martin Schön
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui;

import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 * ChangeTime allows admin to change date and time stored in {@link CurrentTime}
 * 
 * @see CurrentTime
 */
public class ChangeTime extends javax.swing.JFrame {
    private MainGui mainGui;

    public ChangeTime() {
        initComponents();
    }
    
    public void setChangeTime(MainGui mainGui){
        this.mainGui = mainGui;
        this.setVisible(true);
        mainGui.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        closeButton = new javax.swing.JButton();
        setNewTimeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nastavenie času");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(443, 301));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        closeButton.setText("Zavrieť");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        setNewTimeButton.setText("Nastav nový čas");
        setNewTimeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                setNewTimeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(setNewTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Nastav nový dátum a čas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseReleased
        this.mainGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseReleased

    private void setNewTimeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setNewTimeButtonMouseReleased
        if (dateTimePicker1.getDateTimePermissive()== null){
            JOptionPane.showMessageDialog(rootPane, "Zvoľ dátum (a čas)" , "Chyba pri nastavovani času", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(ChangeTime.class.getName()).error("DateTime not set up properly");
            return;
        }
        if (this.mainGui.setCurrentTime(dateTimePicker1.getDateTimePermissive())){
                mainGui.checkStatus();
                this.mainGui.setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_setNewTimeButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setNewTimeButton;
    // End of variables declaration//GEN-END:variables
}
