/*
 * VAVA project
 * Esport League by Martin Schön and Peter Smreček
 * FIIT STU, 2021
 */
package sk.stu.fiit.gui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import sk.stu.fiit.user.LeagueOrganizer;

/**
 *
 * @author PeterSmrecek
 */
public class LeagueWindow extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    
    private final Logger logger = Logger.getLogger(LeagueWindow.class.getName());
    private LeagueOrganizer leagueOrganizer;
    private List<JTextField> tfInfoList;
    
    public LeagueWindow(LeagueOrganizer leagueOrganizer) {
        initComponents();
        
        this.leagueOrganizer = leagueOrganizer;
        
        this.tfInfoList = Arrays.asList(nameTf, gameTf, genreTf, aboutTf, dateStartTf, dateEndTf, ageRestrictionTf, maxTeamsTf, teamsInMatchTf);
        
        updateAll();
        
        
//        atributesCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++", "ABAP", "VBA", "Python", "Ruby", "iOS", "Iné" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg1Bg = new javax.swing.ButtonGroup();
        mainPnl = new javax.swing.JPanel();
        tableScroll = new javax.swing.JScrollPane();
        tableTbl = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        imagePnl = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        controlsPnl = new javax.swing.JPanel();
        createLeagueBtn = new javax.swing.JButton();
        addPrizeBtn = new javax.swing.JButton();
        removePrizeBtn = new javax.swing.JButton();
        addIconBtn = new javax.swing.JButton();
        infoPnl = new javax.swing.JPanel();
        l3Lbl = new javax.swing.JLabel();
        l6Lbl = new javax.swing.JLabel();
        l4Lbl = new javax.swing.JLabel();
        dateEndTf = new javax.swing.JTextField();
        l9Lbl = new javax.swing.JLabel();
        l1Lbl = new javax.swing.JLabel();
        maxTeamsTf = new javax.swing.JTextField();
        l8Lbl = new javax.swing.JLabel();
        dateStartTf = new javax.swing.JTextField();
        gameTf = new javax.swing.JTextField();
        aboutTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        l5Lbl = new javax.swing.JLabel();
        genreTf = new javax.swing.JTextField();
        l2Lbl = new javax.swing.JLabel();
        teamsInMatchTf = new javax.swing.JTextField();
        ageRestrictionTf = new javax.swing.JTextField();
        l7Lbl = new javax.swing.JLabel();
        prizesPnl = new javax.swing.JPanel();
        l1Lbl1 = new javax.swing.JLabel();
        tf1Tf = new javax.swing.JTextField();
        tf2Tf = new javax.swing.JTextField();
        l2Lbl1 = new javax.swing.JLabel();
        l3Lbl1 = new javax.swing.JLabel();
        tf3Tf = new javax.swing.JTextField();
        tf4Tf = new javax.swing.JTextField();
        l4Lbl1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.GridBagLayout mainPnlLayout = new java.awt.GridBagLayout();
        mainPnlLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        mainPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        mainPnl.setLayout(mainPnlLayout);

        tableScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Výhry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        tableScroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableScroll.setPreferredSize(new java.awt.Dimension(462, 100));

        tableTbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umiestnenie", "Názov výhry", "Popis", "Finančná hodnota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTbl.setPreferredSize(new java.awt.Dimension(300, 0));
        tableTbl.getTableHeader().setReorderingAllowed(false);
        tableScroll.setViewportView(tableTbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(tableScroll, gridBagConstraints);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLbl.setText("Vytvorenie ligy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 20;
        mainPnl.add(titleLbl, gridBagConstraints);

        imagePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obrázok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        imagePnl.setLayout(new java.awt.GridBagLayout());

        imageLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imageLbl.setText("[Obrázok]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        imagePnl.add(imageLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(imagePnl, gridBagConstraints);

        controlsPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ovládacie prvky", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        controlsPnl.setLayout(new javax.swing.BoxLayout(controlsPnl, javax.swing.BoxLayout.LINE_AXIS));

        createLeagueBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createLeagueBtn.setText("Vytvoriť ligu");
        createLeagueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createLeagueBtnMouseReleased(evt);
            }
        });
        controlsPnl.add(createLeagueBtn);

        addPrizeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addPrizeBtn.setText("Pridať výhru");
        addPrizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addPrizeBtnMouseReleased(evt);
            }
        });
        controlsPnl.add(addPrizeBtn);

        removePrizeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removePrizeBtn.setText("Odobrať výhru");
        removePrizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                removePrizeBtnMouseReleased(evt);
            }
        });
        controlsPnl.add(removePrizeBtn);

        addIconBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addIconBtn.setText("Zvoliť logo ligy");
        addIconBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addIconBtnMouseReleased(evt);
            }
        });
        controlsPnl.add(addIconBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(controlsPnl, gridBagConstraints);

        infoPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informácie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        java.awt.GridBagLayout infoPnlLayout = new java.awt.GridBagLayout();
        infoPnlLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        infoPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        infoPnl.setLayout(infoPnlLayout);

        l3Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l3Lbl.setText("Žáner");
        l3Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l3Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        infoPnl.add(l3Lbl, gridBagConstraints);

        l6Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l6Lbl.setText("Dátum ukončenia");
        l6Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l6Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        infoPnl.add(l6Lbl, gridBagConstraints);

        l4Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l4Lbl.setText("Popis");
        l4Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l4Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        infoPnl.add(l4Lbl, gridBagConstraints);

        dateEndTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateEndTf.setMinimumSize(new java.awt.Dimension(200, 26));
        dateEndTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(dateEndTf, gridBagConstraints);

        l9Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l9Lbl.setText("Počet tímov v zápase");
        l9Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l9Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        infoPnl.add(l9Lbl, gridBagConstraints);

        l1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l1Lbl.setText("Názov ligy");
        l1Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l1Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        infoPnl.add(l1Lbl, gridBagConstraints);

        maxTeamsTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxTeamsTf.setMinimumSize(new java.awt.Dimension(200, 26));
        maxTeamsTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(maxTeamsTf, gridBagConstraints);

        l8Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l8Lbl.setText("Maximálny počet tímov");
        l8Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l8Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        infoPnl.add(l8Lbl, gridBagConstraints);

        dateStartTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateStartTf.setMinimumSize(new java.awt.Dimension(200, 26));
        dateStartTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(dateStartTf, gridBagConstraints);

        gameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gameTf.setMinimumSize(new java.awt.Dimension(200, 26));
        gameTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(gameTf, gridBagConstraints);

        aboutTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aboutTf.setMinimumSize(new java.awt.Dimension(200, 26));
        aboutTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(aboutTf, gridBagConstraints);

        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTf.setMinimumSize(new java.awt.Dimension(200, 26));
        nameTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(nameTf, gridBagConstraints);

        l5Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l5Lbl.setText("Dátum začiatku");
        l5Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l5Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        infoPnl.add(l5Lbl, gridBagConstraints);

        genreTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genreTf.setMinimumSize(new java.awt.Dimension(200, 26));
        genreTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(genreTf, gridBagConstraints);

        l2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l2Lbl.setText("Hra");
        l2Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l2Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        infoPnl.add(l2Lbl, gridBagConstraints);

        teamsInMatchTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamsInMatchTf.setMinimumSize(new java.awt.Dimension(200, 26));
        teamsInMatchTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(teamsInMatchTf, gridBagConstraints);

        ageRestrictionTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageRestrictionTf.setMinimumSize(new java.awt.Dimension(200, 26));
        ageRestrictionTf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        infoPnl.add(ageRestrictionTf, gridBagConstraints);

        l7Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l7Lbl.setText("Vekové obmedzenie");
        l7Lbl.setMinimumSize(new java.awt.Dimension(200, 26));
        l7Lbl.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        infoPnl.add(l7Lbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(infoPnl, gridBagConstraints);

        prizesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Výhry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        java.awt.GridBagLayout prizesPnlLayout = new java.awt.GridBagLayout();
        prizesPnlLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        prizesPnlLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        prizesPnl.setLayout(prizesPnlLayout);

        l1Lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l1Lbl1.setText("Umiestnenie");
        l1Lbl1.setMinimumSize(new java.awt.Dimension(200, 26));
        l1Lbl1.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        prizesPnl.add(l1Lbl1, gridBagConstraints);

        tf1Tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf1Tf.setMinimumSize(new java.awt.Dimension(200, 26));
        tf1Tf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        prizesPnl.add(tf1Tf, gridBagConstraints);

        tf2Tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf2Tf.setMinimumSize(new java.awt.Dimension(200, 26));
        tf2Tf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        prizesPnl.add(tf2Tf, gridBagConstraints);

        l2Lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l2Lbl1.setText("Názov výhry");
        l2Lbl1.setMinimumSize(new java.awt.Dimension(200, 26));
        l2Lbl1.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        prizesPnl.add(l2Lbl1, gridBagConstraints);

        l3Lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l3Lbl1.setText("Popis");
        l3Lbl1.setMinimumSize(new java.awt.Dimension(200, 26));
        l3Lbl1.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        prizesPnl.add(l3Lbl1, gridBagConstraints);

        tf3Tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf3Tf.setMinimumSize(new java.awt.Dimension(200, 26));
        tf3Tf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        prizesPnl.add(tf3Tf, gridBagConstraints);

        tf4Tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf4Tf.setMinimumSize(new java.awt.Dimension(200, 26));
        tf4Tf.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        prizesPnl.add(tf4Tf, gridBagConstraints);

        l4Lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l4Lbl1.setText("Finančná hodnota");
        l4Lbl1.setMinimumSize(new java.awt.Dimension(200, 26));
        l4Lbl1.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        prizesPnl.add(l4Lbl1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mainPnl.add(prizesPnl, gridBagConstraints);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Súbor");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Otvoriť");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Uložiť");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Uložiť ako");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Skončiť");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Upraviť");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Vystrihnúť");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Kopírovať");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Prilepiť");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Vymazať");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Pomocník");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Obsah");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("O aplikácií");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addPrizeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPrizeBtnMouseReleased
        // TODO add your handling code here:
        addPrizeAction();
    }//GEN-LAST:event_addPrizeBtnMouseReleased

    private void removePrizeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePrizeBtnMouseReleased
        // TODO add your handling code here:
        removePrizeAction();
    }//GEN-LAST:event_removePrizeBtnMouseReleased

    private void addIconBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIconBtnMouseReleased
        // TODO add your handling code here:
        addIconAction();
    }//GEN-LAST:event_addIconBtnMouseReleased

    private void createLeagueBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLeagueBtnMouseReleased
        // TODO add your handling code here:
        createLeagueAction();
    }//GEN-LAST:event_createLeagueBtnMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField aboutTf;
    private javax.swing.JButton addIconBtn;
    private javax.swing.JButton addPrizeBtn;
    private javax.swing.JTextField ageRestrictionTf;
    private javax.swing.ButtonGroup bg1Bg;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JPanel controlsPnl;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JButton createLeagueBtn;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JTextField dateEndTf;
    private javax.swing.JTextField dateStartTf;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField gameTf;
    private javax.swing.JTextField genreTf;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JPanel imagePnl;
    private javax.swing.JPanel infoPnl;
    private javax.swing.JLabel l1Lbl;
    private javax.swing.JLabel l1Lbl1;
    private javax.swing.JLabel l2Lbl;
    private javax.swing.JLabel l2Lbl1;
    private javax.swing.JLabel l3Lbl;
    private javax.swing.JLabel l3Lbl1;
    private javax.swing.JLabel l4Lbl;
    private javax.swing.JLabel l4Lbl1;
    private javax.swing.JLabel l5Lbl;
    private javax.swing.JLabel l6Lbl;
    private javax.swing.JLabel l7Lbl;
    private javax.swing.JLabel l8Lbl;
    private javax.swing.JLabel l9Lbl;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JTextField maxTeamsTf;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nameTf;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JPanel prizesPnl;
    private javax.swing.JButton removePrizeBtn;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JTable tableTbl;
    private javax.swing.JTextField teamsInMatchTf;
    private javax.swing.JTextField tf1Tf;
    private javax.swing.JTextField tf2Tf;
    private javax.swing.JTextField tf3Tf;
    private javax.swing.JTextField tf4Tf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    
    private void updateAll(){
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void addPrizeAction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void removePrizeAction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void addIconAction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void createLeagueAction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void btn5Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void btn6Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void btn7Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void btn8Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void btn9Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void deleteRows(DefaultTableModel model) {
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }

    private void populateCustomersTbl(JTable table, ArrayList list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        deleteRows(model);

        int numberOfColumns = table.getColumnCount();
        Object[] rowData = new Object[numberOfColumns];

        for (int i = 0; i < list.size(); i++) {

//            rowData[0] = list.get(i).getCustomer().getName();
//            rowData[1] = list.get(i).getRoom().getName();
//            rowData[2] = sdfRoom.format(start);
//            rowData[3] = sdfRoom.format(end);
//
//            if (end.after(compareDate)) {
//                rowData[4] = false;
//            } else {
//                rowData[4] = true;
//            }
            model.addRow(rowData);
        }
    }

    private void rb1Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void rb2Action() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
